version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:1.6
    restart: on-failure
    ports:
      - 1883:1883
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
